
namespace StockManagementSystem
{
    partial class Stock
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Stock));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.txtProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSalePrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPurchasePrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cbCategory = new System.Windows.Forms.ComboBox();
            this.dateTime = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnSave = new Bunifu.Framework.UI.BunifuThinButton2();
            this.btnUpdate = new Bunifu.Framework.UI.BunifuThinButton2();
            this.btnDelete = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.brnCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSupplier = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOrders = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnWarehouse = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cbSupplier = new System.Windows.Forms.ComboBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.RoyalBlue;
            this.panel1.Controls.Add(this.bunifuLabel3);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1168, 51);
            this.panel1.TabIndex = 0;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Indigo;
            this.panel2.Controls.Add(this.btnWarehouse);
            this.panel2.Controls.Add(this.btnOrders);
            this.panel2.Controls.Add(this.btnSupplier);
            this.panel2.Controls.Add(this.brnCustomer);
            this.panel2.Controls.Add(this.btnCategory);
            this.panel2.Controls.Add(this.btnUser);
            this.panel2.Location = new System.Drawing.Point(371, 51);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(797, 49);
            this.panel2.TabIndex = 1;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.RoyalBlue;
            this.bunifuLabel1.Location = new System.Drawing.Point(52, 59);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(310, 29);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Stock Management System";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 21;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(0, 57);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(43, 43);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.bunifuPictureBox1.TabIndex = 3;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // txtProductName
            // 
            this.txtProductName.AcceptsReturn = false;
            this.txtProductName.AcceptsTab = false;
            this.txtProductName.AnimationSpeed = 200;
            this.txtProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductName.AutoSizeHeight = true;
            this.txtProductName.BackColor = System.Drawing.Color.White;
            this.txtProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductName.BackgroundImage")));
            this.txtProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductName.BorderRadius = 1;
            this.txtProductName.BorderThickness = 1;
            this.txtProductName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtProductName.DefaultText = "";
            this.txtProductName.FillColor = System.Drawing.Color.White;
            this.txtProductName.HideSelection = true;
            this.txtProductName.IconLeft = null;
            this.txtProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.IconPadding = 10;
            this.txtProductName.IconRight = null;
            this.txtProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.Lines = new string[0];
            this.txtProductName.Location = new System.Drawing.Point(12, 145);
            this.txtProductName.MaxLength = 32767;
            this.txtProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductName.Modified = false;
            this.txtProductName.Multiline = false;
            this.txtProductName.Name = "txtProductName";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtProductName.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnIdleState = stateProperties52;
            this.txtProductName.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductName.PasswordChar = '\0';
            this.txtProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductName.PlaceholderText = "Product Name";
            this.txtProductName.ReadOnly = false;
            this.txtProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductName.SelectedText = "";
            this.txtProductName.SelectionLength = 0;
            this.txtProductName.SelectionStart = 0;
            this.txtProductName.ShortcutsEnabled = true;
            this.txtProductName.Size = new System.Drawing.Size(192, 39);
            this.txtProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductName.TabIndex = 4;
            this.txtProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductName.TextMarginBottom = 0;
            this.txtProductName.TextMarginLeft = 3;
            this.txtProductName.TextMarginTop = 1;
            this.txtProductName.TextPlaceholder = "Product Name";
            this.txtProductName.UseSystemPasswordChar = false;
            this.txtProductName.WordWrap = true;
            // 
            // txtSalePrice
            // 
            this.txtSalePrice.AcceptsReturn = false;
            this.txtSalePrice.AcceptsTab = false;
            this.txtSalePrice.AnimationSpeed = 200;
            this.txtSalePrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSalePrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSalePrice.AutoSizeHeight = true;
            this.txtSalePrice.BackColor = System.Drawing.Color.White;
            this.txtSalePrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSalePrice.BackgroundImage")));
            this.txtSalePrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSalePrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSalePrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSalePrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSalePrice.BorderRadius = 1;
            this.txtSalePrice.BorderThickness = 1;
            this.txtSalePrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSalePrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSalePrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSalePrice.DefaultText = "";
            this.txtSalePrice.FillColor = System.Drawing.Color.White;
            this.txtSalePrice.HideSelection = true;
            this.txtSalePrice.IconLeft = null;
            this.txtSalePrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.IconPadding = 10;
            this.txtSalePrice.IconRight = null;
            this.txtSalePrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalePrice.Lines = new string[0];
            this.txtSalePrice.Location = new System.Drawing.Point(12, 369);
            this.txtSalePrice.MaxLength = 32767;
            this.txtSalePrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSalePrice.Modified = false;
            this.txtSalePrice.Multiline = false;
            this.txtSalePrice.Name = "txtSalePrice";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSalePrice.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalePrice.OnIdleState = stateProperties56;
            this.txtSalePrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtSalePrice.PasswordChar = '\0';
            this.txtSalePrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSalePrice.PlaceholderText = "Sale Price";
            this.txtSalePrice.ReadOnly = false;
            this.txtSalePrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSalePrice.SelectedText = "";
            this.txtSalePrice.SelectionLength = 0;
            this.txtSalePrice.SelectionStart = 0;
            this.txtSalePrice.ShortcutsEnabled = true;
            this.txtSalePrice.Size = new System.Drawing.Size(192, 39);
            this.txtSalePrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSalePrice.TabIndex = 5;
            this.txtSalePrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSalePrice.TextMarginBottom = 0;
            this.txtSalePrice.TextMarginLeft = 3;
            this.txtSalePrice.TextMarginTop = 1;
            this.txtSalePrice.TextPlaceholder = "Sale Price";
            this.txtSalePrice.UseSystemPasswordChar = false;
            this.txtSalePrice.WordWrap = true;
            // 
            // txtQuantity
            // 
            this.txtQuantity.AcceptsReturn = false;
            this.txtQuantity.AcceptsTab = false;
            this.txtQuantity.AnimationSpeed = 200;
            this.txtQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuantity.AutoSizeHeight = true;
            this.txtQuantity.BackColor = System.Drawing.Color.White;
            this.txtQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuantity.BackgroundImage")));
            this.txtQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuantity.BorderRadius = 1;
            this.txtQuantity.BorderThickness = 1;
            this.txtQuantity.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtQuantity.DefaultText = "";
            this.txtQuantity.FillColor = System.Drawing.Color.White;
            this.txtQuantity.HideSelection = true;
            this.txtQuantity.IconLeft = null;
            this.txtQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.IconPadding = 10;
            this.txtQuantity.IconRight = null;
            this.txtQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantity.Lines = new string[0];
            this.txtQuantity.Location = new System.Drawing.Point(12, 254);
            this.txtQuantity.MaxLength = 32767;
            this.txtQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuantity.Modified = false;
            this.txtQuantity.Multiline = false;
            this.txtQuantity.Name = "txtQuantity";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQuantity.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantity.OnIdleState = stateProperties60;
            this.txtQuantity.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuantity.PasswordChar = '\0';
            this.txtQuantity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuantity.PlaceholderText = "Quantity";
            this.txtQuantity.ReadOnly = false;
            this.txtQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuantity.SelectedText = "";
            this.txtQuantity.SelectionLength = 0;
            this.txtQuantity.SelectionStart = 0;
            this.txtQuantity.ShortcutsEnabled = true;
            this.txtQuantity.Size = new System.Drawing.Size(192, 39);
            this.txtQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQuantity.TabIndex = 6;
            this.txtQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuantity.TextMarginBottom = 0;
            this.txtQuantity.TextMarginLeft = 3;
            this.txtQuantity.TextMarginTop = 1;
            this.txtQuantity.TextPlaceholder = "Quantity";
            this.txtQuantity.UseSystemPasswordChar = false;
            this.txtQuantity.WordWrap = true;
            // 
            // txtPurchasePrice
            // 
            this.txtPurchasePrice.AcceptsReturn = false;
            this.txtPurchasePrice.AcceptsTab = false;
            this.txtPurchasePrice.AnimationSpeed = 200;
            this.txtPurchasePrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPurchasePrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPurchasePrice.AutoSizeHeight = true;
            this.txtPurchasePrice.BackColor = System.Drawing.Color.White;
            this.txtPurchasePrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPurchasePrice.BackgroundImage")));
            this.txtPurchasePrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPurchasePrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPurchasePrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPurchasePrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPurchasePrice.BorderRadius = 1;
            this.txtPurchasePrice.BorderThickness = 1;
            this.txtPurchasePrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPurchasePrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPurchasePrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurchasePrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPurchasePrice.DefaultText = "";
            this.txtPurchasePrice.FillColor = System.Drawing.Color.White;
            this.txtPurchasePrice.HideSelection = true;
            this.txtPurchasePrice.IconLeft = null;
            this.txtPurchasePrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurchasePrice.IconPadding = 10;
            this.txtPurchasePrice.IconRight = null;
            this.txtPurchasePrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPurchasePrice.Lines = new string[0];
            this.txtPurchasePrice.Location = new System.Drawing.Point(12, 312);
            this.txtPurchasePrice.MaxLength = 32767;
            this.txtPurchasePrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPurchasePrice.Modified = false;
            this.txtPurchasePrice.Multiline = false;
            this.txtPurchasePrice.Name = "txtPurchasePrice";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurchasePrice.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPurchasePrice.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurchasePrice.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPurchasePrice.OnIdleState = stateProperties64;
            this.txtPurchasePrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtPurchasePrice.PasswordChar = '\0';
            this.txtPurchasePrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPurchasePrice.PlaceholderText = "Purchase Price";
            this.txtPurchasePrice.ReadOnly = false;
            this.txtPurchasePrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPurchasePrice.SelectedText = "";
            this.txtPurchasePrice.SelectionLength = 0;
            this.txtPurchasePrice.SelectionStart = 0;
            this.txtPurchasePrice.ShortcutsEnabled = true;
            this.txtPurchasePrice.Size = new System.Drawing.Size(192, 39);
            this.txtPurchasePrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPurchasePrice.TabIndex = 7;
            this.txtPurchasePrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPurchasePrice.TextMarginBottom = 0;
            this.txtPurchasePrice.TextMarginLeft = 3;
            this.txtPurchasePrice.TextMarginTop = 1;
            this.txtPurchasePrice.TextPlaceholder = "Purchase Price";
            this.txtPurchasePrice.UseSystemPasswordChar = false;
            this.txtPurchasePrice.WordWrap = true;
            // 
            // cbCategory
            // 
            this.cbCategory.FormattingEnabled = true;
            this.cbCategory.Items.AddRange(new object[] {
            "Brake",
            "Clutch",
            "Fuel",
            "Suspension",
            "Steering wheel",
            "Electric",
            "Gearbox"});
            this.cbCategory.Location = new System.Drawing.Point(12, 205);
            this.cbCategory.Name = "cbCategory";
            this.cbCategory.Size = new System.Drawing.Size(192, 27);
            this.cbCategory.TabIndex = 8;
            this.cbCategory.Text = "Category";
            // 
            // dateTime
            // 
            this.dateTime.BackColor = System.Drawing.Color.Transparent;
            this.dateTime.BorderColor = System.Drawing.Color.Silver;
            this.dateTime.BorderRadius = 1;
            this.dateTime.Color = System.Drawing.Color.Silver;
            this.dateTime.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateTime.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateTime.DisabledColor = System.Drawing.Color.Gray;
            this.dateTime.DisplayWeekNumbers = false;
            this.dateTime.DPHeight = 0;
            this.dateTime.FillDatePicker = false;
            this.dateTime.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.dateTime.ForeColor = System.Drawing.Color.Black;
            this.dateTime.Icon = ((System.Drawing.Image)(resources.GetObject("dateTime.Icon")));
            this.dateTime.IconColor = System.Drawing.Color.Gray;
            this.dateTime.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateTime.LeftTextMargin = 5;
            this.dateTime.Location = new System.Drawing.Point(12, 426);
            this.dateTime.MinimumSize = new System.Drawing.Size(0, 32);
            this.dateTime.Name = "dateTime";
            this.dateTime.Size = new System.Drawing.Size(192, 32);
            this.dateTime.TabIndex = 9;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle10.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle10;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle11.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            dataGridViewCellStyle11.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle11.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
            this.bunifuDataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle12.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            dataGridViewCellStyle12.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle12.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle12;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(251, 145);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(895, 388);
            this.bunifuDataGridView1.TabIndex = 10;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnSave
            // 
            this.btnSave.ActiveBorderThickness = 1;
            this.btnSave.ActiveCornerRadius = 20;
            this.btnSave.ActiveFillColor = System.Drawing.Color.RoyalBlue;
            this.btnSave.ActiveForecolor = System.Drawing.Color.RoyalBlue;
            this.btnSave.ActiveLineColor = System.Drawing.Color.RoyalBlue;
            this.btnSave.BackColor = System.Drawing.Color.White;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.ButtonText = "Save";
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnSave.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.ForeColor = System.Drawing.Color.RoyalBlue;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleCornerRadius = 20;
            this.btnSave.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnSave.IdleForecolor = System.Drawing.Color.White;
            this.btnSave.IdleLineColor = System.Drawing.Color.RoyalBlue;
            this.btnSave.Location = new System.Drawing.Point(14, 505);
            this.btnSave.Margin = new System.Windows.Forms.Padding(5);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(181, 41);
            this.btnSave.TabIndex = 11;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnUpdate
            // 
            this.btnUpdate.ActiveBorderThickness = 1;
            this.btnUpdate.ActiveCornerRadius = 20;
            this.btnUpdate.ActiveFillColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.ActiveForecolor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.ActiveLineColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.BackColor = System.Drawing.Color.White;
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.ButtonText = "Update";
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnUpdate.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUpdate.ForeColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.IdleBorderThickness = 1;
            this.btnUpdate.IdleCornerRadius = 20;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.IdleForecolor = System.Drawing.Color.White;
            this.btnUpdate.IdleLineColor = System.Drawing.Color.RoyalBlue;
            this.btnUpdate.Location = new System.Drawing.Point(14, 542);
            this.btnUpdate.Margin = new System.Windows.Forms.Padding(5);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new System.Drawing.Size(181, 41);
            this.btnUpdate.TabIndex = 12;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnDelete
            // 
            this.btnDelete.ActiveBorderThickness = 1;
            this.btnDelete.ActiveCornerRadius = 20;
            this.btnDelete.ActiveFillColor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.ActiveForecolor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.ActiveLineColor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.BackColor = System.Drawing.Color.White;
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnDelete.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelete.ForeColor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.IdleBorderThickness = 1;
            this.btnDelete.IdleCornerRadius = 20;
            this.btnDelete.IdleFillColor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.IdleForecolor = System.Drawing.Color.White;
            this.btnDelete.IdleLineColor = System.Drawing.Color.RoyalBlue;
            this.btnDelete.Location = new System.Drawing.Point(14, 578);
            this.btnDelete.Margin = new System.Windows.Forms.Padding(5);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(181, 41);
            this.btnDelete.TabIndex = 13;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.RoyalBlue;
            this.bunifuLabel2.Location = new System.Drawing.Point(612, 108);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(163, 29);
            this.bunifuLabel2.TabIndex = 14;
            this.bunifuLabel2.Text = "Product   Stock";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(421, 5);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(310, 29);
            this.bunifuLabel3.TabIndex = 15;
            this.bunifuLabel3.Text = "Stock Management System";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnUser
            // 
            this.btnUser.AllowAnimations = true;
            this.btnUser.AllowMouseEffects = true;
            this.btnUser.AllowToggling = false;
            this.btnUser.AnimationSpeed = 200;
            this.btnUser.AutoGenerateColors = false;
            this.btnUser.AutoRoundBorders = false;
            this.btnUser.AutoSizeLeftIcon = true;
            this.btnUser.AutoSizeRightIcon = true;
            this.btnUser.BackColor = System.Drawing.Color.Transparent;
            this.btnUser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUser.BackgroundImage")));
            this.btnUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.ButtonText = "User";
            this.btnUser.ButtonTextMarginLeft = 0;
            this.btnUser.ColorContrastOnClick = 45;
            this.btnUser.ColorContrastOnHover = 45;
            this.btnUser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.btnUser.CustomizableEdges = borderEdges19;
            this.btnUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUser.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUser.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUser.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnUser.ForeColor = System.Drawing.Color.White;
            this.btnUser.IconLeft = null;
            this.btnUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUser.IconMarginLeft = 11;
            this.btnUser.IconPadding = 10;
            this.btnUser.IconRight = null;
            this.btnUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUser.IconSize = 25;
            this.btnUser.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUser.IdleBorderRadius = 0;
            this.btnUser.IdleBorderThickness = 0;
            this.btnUser.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUser.IdleIconLeftImage = null;
            this.btnUser.IdleIconRightImage = null;
            this.btnUser.IndicateFocus = false;
            this.btnUser.Location = new System.Drawing.Point(27, 9);
            this.btnUser.Name = "btnUser";
            this.btnUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUser.OnDisabledState.BorderRadius = 1;
            this.btnUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnDisabledState.BorderThickness = 1;
            this.btnUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUser.OnDisabledState.IconLeftImage = null;
            this.btnUser.OnDisabledState.IconRightImage = null;
            this.btnUser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnUser.onHoverState.BorderRadius = 1;
            this.btnUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.onHoverState.BorderThickness = 1;
            this.btnUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnUser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUser.onHoverState.IconLeftImage = null;
            this.btnUser.onHoverState.IconRightImage = null;
            this.btnUser.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnUser.OnIdleState.BorderRadius = 1;
            this.btnUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnIdleState.BorderThickness = 1;
            this.btnUser.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnUser.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUser.OnIdleState.IconLeftImage = null;
            this.btnUser.OnIdleState.IconRightImage = null;
            this.btnUser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUser.OnPressedState.BorderRadius = 1;
            this.btnUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUser.OnPressedState.BorderThickness = 1;
            this.btnUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUser.OnPressedState.IconLeftImage = null;
            this.btnUser.OnPressedState.IconRightImage = null;
            this.btnUser.Size = new System.Drawing.Size(88, 31);
            this.btnUser.TabIndex = 15;
            this.btnUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUser.TextMarginLeft = 0;
            this.btnUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUser.UseDefaultRadiusAndThickness = true;
            // 
            // btnCategory
            // 
            this.btnCategory.AllowAnimations = true;
            this.btnCategory.AllowMouseEffects = true;
            this.btnCategory.AllowToggling = false;
            this.btnCategory.AnimationSpeed = 200;
            this.btnCategory.AutoGenerateColors = false;
            this.btnCategory.AutoRoundBorders = false;
            this.btnCategory.AutoSizeLeftIcon = true;
            this.btnCategory.AutoSizeRightIcon = true;
            this.btnCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnCategory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategory.BackgroundImage")));
            this.btnCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.ButtonText = "Category";
            this.btnCategory.ButtonTextMarginLeft = 0;
            this.btnCategory.ColorContrastOnClick = 45;
            this.btnCategory.ColorContrastOnHover = 45;
            this.btnCategory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btnCategory.CustomizableEdges = borderEdges20;
            this.btnCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategory.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCategory.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategory.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnCategory.ForeColor = System.Drawing.Color.White;
            this.btnCategory.IconLeft = null;
            this.btnCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategory.IconMarginLeft = 11;
            this.btnCategory.IconPadding = 10;
            this.btnCategory.IconRight = null;
            this.btnCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCategory.IconSize = 25;
            this.btnCategory.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCategory.IdleBorderRadius = 0;
            this.btnCategory.IdleBorderThickness = 0;
            this.btnCategory.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCategory.IdleIconLeftImage = null;
            this.btnCategory.IdleIconRightImage = null;
            this.btnCategory.IndicateFocus = false;
            this.btnCategory.Location = new System.Drawing.Point(174, 9);
            this.btnCategory.Name = "btnCategory";
            this.btnCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategory.OnDisabledState.BorderRadius = 1;
            this.btnCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnDisabledState.BorderThickness = 1;
            this.btnCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategory.OnDisabledState.IconLeftImage = null;
            this.btnCategory.OnDisabledState.IconRightImage = null;
            this.btnCategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCategory.onHoverState.BorderRadius = 1;
            this.btnCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.onHoverState.BorderThickness = 1;
            this.btnCategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.onHoverState.IconLeftImage = null;
            this.btnCategory.onHoverState.IconRightImage = null;
            this.btnCategory.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCategory.OnIdleState.BorderRadius = 1;
            this.btnCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnIdleState.BorderThickness = 1;
            this.btnCategory.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.OnIdleState.IconLeftImage = null;
            this.btnCategory.OnIdleState.IconRightImage = null;
            this.btnCategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategory.OnPressedState.BorderRadius = 1;
            this.btnCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategory.OnPressedState.BorderThickness = 1;
            this.btnCategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategory.OnPressedState.IconLeftImage = null;
            this.btnCategory.OnPressedState.IconRightImage = null;
            this.btnCategory.Size = new System.Drawing.Size(88, 31);
            this.btnCategory.TabIndex = 17;
            this.btnCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategory.TextMarginLeft = 0;
            this.btnCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategory.UseDefaultRadiusAndThickness = true;
            // 
            // brnCustomer
            // 
            this.brnCustomer.AllowAnimations = true;
            this.brnCustomer.AllowMouseEffects = true;
            this.brnCustomer.AllowToggling = false;
            this.brnCustomer.AnimationSpeed = 200;
            this.brnCustomer.AutoGenerateColors = false;
            this.brnCustomer.AutoRoundBorders = false;
            this.brnCustomer.AutoSizeLeftIcon = true;
            this.brnCustomer.AutoSizeRightIcon = true;
            this.brnCustomer.BackColor = System.Drawing.Color.Transparent;
            this.brnCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.brnCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("brnCustomer.BackgroundImage")));
            this.brnCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.brnCustomer.ButtonText = "Customer";
            this.brnCustomer.ButtonTextMarginLeft = 0;
            this.brnCustomer.ColorContrastOnClick = 45;
            this.brnCustomer.ColorContrastOnHover = 45;
            this.brnCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = true;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = true;
            borderEdges21.TopRight = true;
            this.brnCustomer.CustomizableEdges = borderEdges21;
            this.brnCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.brnCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.brnCustomer.DisabledFillColor = System.Drawing.Color.Empty;
            this.brnCustomer.DisabledForecolor = System.Drawing.Color.Empty;
            this.brnCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.brnCustomer.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.brnCustomer.ForeColor = System.Drawing.Color.White;
            this.brnCustomer.IconLeft = null;
            this.brnCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.brnCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.brnCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.brnCustomer.IconMarginLeft = 11;
            this.brnCustomer.IconPadding = 10;
            this.brnCustomer.IconRight = null;
            this.brnCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.brnCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.brnCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.brnCustomer.IconSize = 25;
            this.brnCustomer.IdleBorderColor = System.Drawing.Color.Empty;
            this.brnCustomer.IdleBorderRadius = 0;
            this.brnCustomer.IdleBorderThickness = 0;
            this.brnCustomer.IdleFillColor = System.Drawing.Color.Empty;
            this.brnCustomer.IdleIconLeftImage = null;
            this.brnCustomer.IdleIconRightImage = null;
            this.brnCustomer.IndicateFocus = false;
            this.brnCustomer.Location = new System.Drawing.Point(316, 9);
            this.brnCustomer.Name = "brnCustomer";
            this.brnCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.brnCustomer.OnDisabledState.BorderRadius = 1;
            this.brnCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.brnCustomer.OnDisabledState.BorderThickness = 1;
            this.brnCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.brnCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.brnCustomer.OnDisabledState.IconLeftImage = null;
            this.brnCustomer.OnDisabledState.IconRightImage = null;
            this.brnCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.brnCustomer.onHoverState.BorderRadius = 1;
            this.brnCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.brnCustomer.onHoverState.BorderThickness = 1;
            this.brnCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.brnCustomer.onHoverState.ForeColor = System.Drawing.Color.White;
            this.brnCustomer.onHoverState.IconLeftImage = null;
            this.brnCustomer.onHoverState.IconRightImage = null;
            this.brnCustomer.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.brnCustomer.OnIdleState.BorderRadius = 1;
            this.brnCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.brnCustomer.OnIdleState.BorderThickness = 1;
            this.brnCustomer.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.brnCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.brnCustomer.OnIdleState.IconLeftImage = null;
            this.brnCustomer.OnIdleState.IconRightImage = null;
            this.brnCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.brnCustomer.OnPressedState.BorderRadius = 1;
            this.brnCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.brnCustomer.OnPressedState.BorderThickness = 1;
            this.brnCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.brnCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.brnCustomer.OnPressedState.IconLeftImage = null;
            this.brnCustomer.OnPressedState.IconRightImage = null;
            this.brnCustomer.Size = new System.Drawing.Size(88, 31);
            this.brnCustomer.TabIndex = 18;
            this.brnCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.brnCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.brnCustomer.TextMarginLeft = 0;
            this.brnCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.brnCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // btnSupplier
            // 
            this.btnSupplier.AllowAnimations = true;
            this.btnSupplier.AllowMouseEffects = true;
            this.btnSupplier.AllowToggling = false;
            this.btnSupplier.AnimationSpeed = 200;
            this.btnSupplier.AutoGenerateColors = false;
            this.btnSupplier.AutoRoundBorders = false;
            this.btnSupplier.AutoSizeLeftIcon = true;
            this.btnSupplier.AutoSizeRightIcon = true;
            this.btnSupplier.BackColor = System.Drawing.Color.Transparent;
            this.btnSupplier.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSupplier.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSupplier.BackgroundImage")));
            this.btnSupplier.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSupplier.ButtonText = "Supplier";
            this.btnSupplier.ButtonTextMarginLeft = 0;
            this.btnSupplier.ColorContrastOnClick = 45;
            this.btnSupplier.ColorContrastOnHover = 45;
            this.btnSupplier.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.btnSupplier.CustomizableEdges = borderEdges22;
            this.btnSupplier.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSupplier.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSupplier.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSupplier.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSupplier.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSupplier.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnSupplier.ForeColor = System.Drawing.Color.White;
            this.btnSupplier.IconLeft = null;
            this.btnSupplier.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSupplier.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSupplier.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSupplier.IconMarginLeft = 11;
            this.btnSupplier.IconPadding = 10;
            this.btnSupplier.IconRight = null;
            this.btnSupplier.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSupplier.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSupplier.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSupplier.IconSize = 25;
            this.btnSupplier.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSupplier.IdleBorderRadius = 0;
            this.btnSupplier.IdleBorderThickness = 0;
            this.btnSupplier.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSupplier.IdleIconLeftImage = null;
            this.btnSupplier.IdleIconRightImage = null;
            this.btnSupplier.IndicateFocus = false;
            this.btnSupplier.Location = new System.Drawing.Point(447, 9);
            this.btnSupplier.Name = "btnSupplier";
            this.btnSupplier.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSupplier.OnDisabledState.BorderRadius = 1;
            this.btnSupplier.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSupplier.OnDisabledState.BorderThickness = 1;
            this.btnSupplier.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSupplier.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSupplier.OnDisabledState.IconLeftImage = null;
            this.btnSupplier.OnDisabledState.IconRightImage = null;
            this.btnSupplier.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSupplier.onHoverState.BorderRadius = 1;
            this.btnSupplier.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSupplier.onHoverState.BorderThickness = 1;
            this.btnSupplier.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSupplier.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSupplier.onHoverState.IconLeftImage = null;
            this.btnSupplier.onHoverState.IconRightImage = null;
            this.btnSupplier.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSupplier.OnIdleState.BorderRadius = 1;
            this.btnSupplier.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSupplier.OnIdleState.BorderThickness = 1;
            this.btnSupplier.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSupplier.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSupplier.OnIdleState.IconLeftImage = null;
            this.btnSupplier.OnIdleState.IconRightImage = null;
            this.btnSupplier.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSupplier.OnPressedState.BorderRadius = 1;
            this.btnSupplier.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSupplier.OnPressedState.BorderThickness = 1;
            this.btnSupplier.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSupplier.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSupplier.OnPressedState.IconLeftImage = null;
            this.btnSupplier.OnPressedState.IconRightImage = null;
            this.btnSupplier.Size = new System.Drawing.Size(88, 31);
            this.btnSupplier.TabIndex = 19;
            this.btnSupplier.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSupplier.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSupplier.TextMarginLeft = 0;
            this.btnSupplier.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSupplier.UseDefaultRadiusAndThickness = true;
            // 
            // btnOrders
            // 
            this.btnOrders.AllowAnimations = true;
            this.btnOrders.AllowMouseEffects = true;
            this.btnOrders.AllowToggling = false;
            this.btnOrders.AnimationSpeed = 200;
            this.btnOrders.AutoGenerateColors = false;
            this.btnOrders.AutoRoundBorders = false;
            this.btnOrders.AutoSizeLeftIcon = true;
            this.btnOrders.AutoSizeRightIcon = true;
            this.btnOrders.BackColor = System.Drawing.Color.Transparent;
            this.btnOrders.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnOrders.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrders.BackgroundImage")));
            this.btnOrders.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrders.ButtonText = "Orders";
            this.btnOrders.ButtonTextMarginLeft = 0;
            this.btnOrders.ColorContrastOnClick = 45;
            this.btnOrders.ColorContrastOnHover = 45;
            this.btnOrders.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.btnOrders.CustomizableEdges = borderEdges23;
            this.btnOrders.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrders.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrders.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnOrders.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnOrders.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOrders.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnOrders.ForeColor = System.Drawing.Color.White;
            this.btnOrders.IconLeft = null;
            this.btnOrders.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrders.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrders.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOrders.IconMarginLeft = 11;
            this.btnOrders.IconPadding = 10;
            this.btnOrders.IconRight = null;
            this.btnOrders.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrders.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrders.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrders.IconSize = 25;
            this.btnOrders.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnOrders.IdleBorderRadius = 0;
            this.btnOrders.IdleBorderThickness = 0;
            this.btnOrders.IdleFillColor = System.Drawing.Color.Empty;
            this.btnOrders.IdleIconLeftImage = null;
            this.btnOrders.IdleIconRightImage = null;
            this.btnOrders.IndicateFocus = false;
            this.btnOrders.Location = new System.Drawing.Point(580, 9);
            this.btnOrders.Name = "btnOrders";
            this.btnOrders.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrders.OnDisabledState.BorderRadius = 1;
            this.btnOrders.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrders.OnDisabledState.BorderThickness = 1;
            this.btnOrders.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrders.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrders.OnDisabledState.IconLeftImage = null;
            this.btnOrders.OnDisabledState.IconRightImage = null;
            this.btnOrders.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnOrders.onHoverState.BorderRadius = 1;
            this.btnOrders.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrders.onHoverState.BorderThickness = 1;
            this.btnOrders.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnOrders.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOrders.onHoverState.IconLeftImage = null;
            this.btnOrders.onHoverState.IconRightImage = null;
            this.btnOrders.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnOrders.OnIdleState.BorderRadius = 1;
            this.btnOrders.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrders.OnIdleState.BorderThickness = 1;
            this.btnOrders.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnOrders.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnOrders.OnIdleState.IconLeftImage = null;
            this.btnOrders.OnIdleState.IconRightImage = null;
            this.btnOrders.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOrders.OnPressedState.BorderRadius = 1;
            this.btnOrders.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrders.OnPressedState.BorderThickness = 1;
            this.btnOrders.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnOrders.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOrders.OnPressedState.IconLeftImage = null;
            this.btnOrders.OnPressedState.IconRightImage = null;
            this.btnOrders.Size = new System.Drawing.Size(88, 31);
            this.btnOrders.TabIndex = 20;
            this.btnOrders.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOrders.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrders.TextMarginLeft = 0;
            this.btnOrders.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOrders.UseDefaultRadiusAndThickness = true;
            // 
            // btnWarehouse
            // 
            this.btnWarehouse.AllowAnimations = true;
            this.btnWarehouse.AllowMouseEffects = true;
            this.btnWarehouse.AllowToggling = false;
            this.btnWarehouse.AnimationSpeed = 200;
            this.btnWarehouse.AutoGenerateColors = false;
            this.btnWarehouse.AutoRoundBorders = false;
            this.btnWarehouse.AutoSizeLeftIcon = true;
            this.btnWarehouse.AutoSizeRightIcon = true;
            this.btnWarehouse.BackColor = System.Drawing.Color.Transparent;
            this.btnWarehouse.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnWarehouse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnWarehouse.BackgroundImage")));
            this.btnWarehouse.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarehouse.ButtonText = "Warehouse";
            this.btnWarehouse.ButtonTextMarginLeft = 0;
            this.btnWarehouse.ColorContrastOnClick = 45;
            this.btnWarehouse.ColorContrastOnHover = 45;
            this.btnWarehouse.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.btnWarehouse.CustomizableEdges = borderEdges24;
            this.btnWarehouse.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnWarehouse.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWarehouse.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnWarehouse.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnWarehouse.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnWarehouse.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnWarehouse.ForeColor = System.Drawing.Color.White;
            this.btnWarehouse.IconLeft = null;
            this.btnWarehouse.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnWarehouse.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnWarehouse.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnWarehouse.IconMarginLeft = 11;
            this.btnWarehouse.IconPadding = 10;
            this.btnWarehouse.IconRight = null;
            this.btnWarehouse.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnWarehouse.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnWarehouse.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnWarehouse.IconSize = 25;
            this.btnWarehouse.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnWarehouse.IdleBorderRadius = 0;
            this.btnWarehouse.IdleBorderThickness = 0;
            this.btnWarehouse.IdleFillColor = System.Drawing.Color.Empty;
            this.btnWarehouse.IdleIconLeftImage = null;
            this.btnWarehouse.IdleIconRightImage = null;
            this.btnWarehouse.IndicateFocus = false;
            this.btnWarehouse.Location = new System.Drawing.Point(697, 9);
            this.btnWarehouse.Name = "btnWarehouse";
            this.btnWarehouse.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWarehouse.OnDisabledState.BorderRadius = 1;
            this.btnWarehouse.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarehouse.OnDisabledState.BorderThickness = 1;
            this.btnWarehouse.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWarehouse.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWarehouse.OnDisabledState.IconLeftImage = null;
            this.btnWarehouse.OnDisabledState.IconRightImage = null;
            this.btnWarehouse.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnWarehouse.onHoverState.BorderRadius = 1;
            this.btnWarehouse.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarehouse.onHoverState.BorderThickness = 1;
            this.btnWarehouse.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnWarehouse.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnWarehouse.onHoverState.IconLeftImage = null;
            this.btnWarehouse.onHoverState.IconRightImage = null;
            this.btnWarehouse.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnWarehouse.OnIdleState.BorderRadius = 1;
            this.btnWarehouse.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarehouse.OnIdleState.BorderThickness = 1;
            this.btnWarehouse.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnWarehouse.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnWarehouse.OnIdleState.IconLeftImage = null;
            this.btnWarehouse.OnIdleState.IconRightImage = null;
            this.btnWarehouse.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWarehouse.OnPressedState.BorderRadius = 1;
            this.btnWarehouse.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnWarehouse.OnPressedState.BorderThickness = 1;
            this.btnWarehouse.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWarehouse.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnWarehouse.OnPressedState.IconLeftImage = null;
            this.btnWarehouse.OnPressedState.IconRightImage = null;
            this.btnWarehouse.Size = new System.Drawing.Size(88, 31);
            this.btnWarehouse.TabIndex = 21;
            this.btnWarehouse.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnWarehouse.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnWarehouse.TextMarginLeft = 0;
            this.btnWarehouse.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnWarehouse.UseDefaultRadiusAndThickness = true;
            // 
            // cbSupplier
            // 
            this.cbSupplier.FormattingEnabled = true;
            this.cbSupplier.Items.AddRange(new object[] {
            "Iveco",
            "Renault",
            "Ford",
            "Mercedes",
            "Hyundai",
            "Skoda"});
            this.cbSupplier.Location = new System.Drawing.Point(12, 470);
            this.cbSupplier.Name = "cbSupplier";
            this.cbSupplier.Size = new System.Drawing.Size(192, 27);
            this.cbSupplier.TabIndex = 15;
            this.cbSupplier.Text = "Supplier";
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // Stock
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 19F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1168, 671);
            this.Controls.Add(this.cbSupplier);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.dateTime);
            this.Controls.Add(this.cbCategory);
            this.Controls.Add(this.txtPurchasePrice);
            this.Controls.Add(this.txtQuantity);
            this.Controls.Add(this.txtSalePrice);
            this.Controls.Add(this.txtProductName);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(5, 4, 5, 4);
            this.Name = "Stock";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Stock";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductName;
        private Bunifu.UI.WinForms.BunifuTextBox txtSalePrice;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuantity;
        private Bunifu.UI.WinForms.BunifuTextBox txtPurchasePrice;
        private System.Windows.Forms.ComboBox cbCategory;
        private Bunifu.UI.WinForms.BunifuDatePicker dateTime;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.Framework.UI.BunifuThinButton2 btnSave;
        private Bunifu.Framework.UI.BunifuThinButton2 btnUpdate;
        private Bunifu.Framework.UI.BunifuThinButton2 btnDelete;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnWarehouse;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOrders;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSupplier;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton brnCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUser;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.ComboBox cbSupplier;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}